# Generated by Django 4.2.10 on 2026-02-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名文档', max_length=255, verbose_name='标题')),
                ('type', models.CharField(choices=[('doc', '富文本文档'), ('sheet', '表格文档')], max_length=20, verbose_name='类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'document',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['creator', '-updated_at'], name='document_creator_53584d_idx'), models.Index(fields=['type'], name='document_type_112a60_idx'), models.Index(fields=['is_deleted'], name='document_is_dele_b6dd59_idx')],
            },
        ),
    ]
