# Generated by Django 4.2.10 on 2026-02-14 04:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'odt', 'rtf', 'txt', 'html', 'htm', 'xlsx', 'xls', 'ods', 'csv', 'pptx', 'ppt', 'odp'])], verbose_name='文档文件'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='文档唯一标识'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL, verbose_name='锁定用户'),
        ),
        migrations.AddField(
            model_name='document',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='编辑会话ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('word', 'Word文档'), ('cell', 'Excel表格'), ('slide', 'PPT演示')], default='word', max_length=20, verbose_name='类型'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_key'], name='document_file_ke_a19e98_idx'),
        ),
    ]
