# Generated by Django 4.2.10 on 2026-02-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workflow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务说明')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('closed', '已关闭'), ('completed', '已完成')], default='active', max_length=20, verbose_name='任务状态')),
                ('aggregation_rules', models.JSONField(blank=True, default=dict, verbose_name='汇总规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('target_departments', models.ManyToManyField(blank=True, related_name='distribution_tasks', to='accounts.department', verbose_name='目标部门')),
                ('target_organizations', models.ManyToManyField(blank=True, related_name='distribution_tasks', to='accounts.organization', verbose_name='目标组织')),
                ('target_users', models.ManyToManyField(blank=True, related_name='assigned_distribution_tasks', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'db_table': 'workflow_distribution_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to=workflow.models.template_upload_to, verbose_name='模板文件')),
                ('editable_cells', models.JSONField(blank=True, default=list, verbose_name='可填单元格配置')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='workflow.template', verbose_name='来源模板')),
            ],
            options={
                'db_table': 'workflow_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('draft', '草稿'), ('submitted', '已上报'), ('returned', '已退回'), ('approved', '已通过'), ('withdrawn', '已撤回'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='上报时间')),
                ('returned_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='accounts.department', verbose_name='部门')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='accounts.organization', verbose_name='组织')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflow.distributiontask', verbose_name='任务')),
            ],
            options={
                'db_table': 'workflow_task_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=workflow.models.submission_upload_to, verbose_name='填报文件')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='提取数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已上报'), ('returned', '已退回'), ('withdrawn', '已撤回'), ('approved', '已通过')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='上报时间')),
                ('returned_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='workflow.taskassignment', verbose_name='任务实例')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='accounts.organization', verbose_name='组织')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workflow.distributiontask', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='填报人')),
            ],
            options={
                'db_table': 'workflow_submission',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='distributiontask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.template', verbose_name='模板'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='workflow_te_is_acti_97dc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['name'], name='workflow_te_name_133b35_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_by', '-created_at'], name='workflow_te_created_4d0150_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status'], name='workflow_ta_status_eef597_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['assignee', '-created_at'], name='workflow_ta_assigne_d85fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'status'], name='workflow_ta_task_id_10716d_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'assignee'), name='uniq_task_assignee_assignment'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='workflow_su_status_a7838d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', 'status'], name='workflow_su_task_id_e09adb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-updated_at'], name='workflow_su_user_id_9bd98c_idx'),
        ),
        migrations.AddIndex(
            model_name='distributiontask',
            index=models.Index(fields=['status'], name='workflow_di_status_999102_idx'),
        ),
        migrations.AddIndex(
            model_name='distributiontask',
            index=models.Index(fields=['deadline'], name='workflow_di_deadlin_5ceb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='distributiontask',
            index=models.Index(fields=['created_by', '-created_at'], name='workflow_di_created_78402c_idx'),
        ),
    ]
