# Generated by Django 4.2.10 on 2026-02-20 11:05

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontask',
            name='template_snapshot_file',
            field=models.FileField(blank=True, null=True, upload_to=workflow.models.task_template_snapshot_upload_to, verbose_name='模板文件快照'),
        ),
        migrations.AddField(
            model_name='distributiontask',
            name='template_version',
            field=models.PositiveIntegerField(default=1, verbose_name='模板版本快照'),
        ),
    ]
