# Generated by Django 4.2.10 on 2026-02-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.file_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=255, verbose_name='MIME类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploader', '-created_at'], name='file_uploade_76f68d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_deleted'], name='file_is_dele_4bfe9f_idx'),
        ),
    ]
