# Generated by Django 4.2.10 on 2026-02-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='file_uploade_168a0a_idx',
            old_name='file_uploade_76f68d_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='file_is_dele_b421c5_idx',
            old_name='file_is_dele_4bfe9f_idx',
        ),
    ]
