# Generated by Django 4.2.10 on 2026-02-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_remove_document_content_document_file_and_more'),
        ('files', '0002_rename_file_uploade_76f68d_idx_file_uploade_168a0a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEditableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_source_links', to='documents.document', verbose_name='在线文档')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editable_links', to='files.file', verbose_name='源文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_editable_links', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文件可编辑映射',
                'verbose_name_plural': '文件可编辑映射',
                'db_table': 'file_editable_document',
            },
        ),
        migrations.AddConstraint(
            model_name='fileeditabledocument',
            constraint=models.UniqueConstraint(fields=('file', 'user'), name='uniq_file_user_editable_doc'),
        ),
    ]
