# Generated by Django 4.2.10 on 2026-02-14 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('documents', '0002_remove_document_content_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', '只读'), ('write', '可编辑')], default='read', max_length=20, verbose_name='权限')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='分享时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='文档')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file', verbose_name='文件')),
                ('sharee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_to', to=settings.AUTH_USER_MODEL, verbose_name='被分享者')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
                'db_table': 'share',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['sharer', '-shared_at'], name='share_sharer__ba1d8d_idx'), models.Index(fields=['sharee', '-shared_at'], name='share_sharee__3794e3_idx'), models.Index(fields=['document'], name='share_documen_fb0395_idx'), models.Index(fields=['file'], name='share_file_id_6f437d_idx'), models.Index(fields=['is_active'], name='share_is_acti_0379c9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(check=models.Q(('document__isnull', False), ('file__isnull', False), _connector='OR'), name='share_document_or_file_not_null'),
        ),
    ]
